import './globals.css'
import { ClerkProvider } from '@clerk/nextjs'
import { Poppins, Lato, Roboto } from 'next/font/google' // Only Poppins font is loaded globally
import { Metadata } from 'next'

const poppins = Poppins({ subsets: ['latin'], weight: ['400', '600'] })
const lato = Lato({ subsets: ['latin'], weight: ['400', '700'] })
const roboto = Roboto({ subsets: ['latin'], weight: ['400', '700'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body
          className={`${lato.className} flex h-screen bg-cover bg-center items-center justify-center w-full`}>
          {children} {/* Render children of each page */}
        </body>
      </html>
    </ClerkProvider>
  )
}
